---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
api_token <- "N64VhW8.yChkBUIJeosGojQ7CSR2xwLf3Qy7Apw464"

get_vorgang(n_max = 200, api_token, start_date = "2020-01-01", end_date = "2020-01-01")


f <- get_documents(type = "plenarprotokoll-text", n_max = 100, api_token = api_token, end_date = "2021-01-01")


f

out <- httr::GET("https://search.dip.bundestag.de/api/v1/drucksache-text?&apikey=N64VhW8.yChkBUIJeosGojQ7CSR2xwLf3Qy7Apw464") %>%
  httr::content()

out$documents[[5]]$ressort
f$autoren_anzeige[[1]]

aktivitaet Metadaten zu Aktivit채ten
drucksache Metadaten zu Drucksachen
drucksache-text Soweit vorhanden werden zus채tzlich die Volltexte der Drucksachen ausgegeben
person Personenstammdaten
plenarprotokoll Metadaten zu Plenarprotokollen
plenarprotokoll-text Soweit vorhanden werden zus채tzlich die Volltexte der Plenarprotokolle ausgegeben
vorgang Metadaten zu Vorg채ngen
vorgangsposition

f %>%
  tidyr::unnest(person_roles, names_repair = ~paste0("roles_", .x))
f$text[1]
```

